touch created-file-1.txt
touch created-file-2.png
touch created-file-3.txt
touch created-file-4.png
touch created-file-5.txt
touch created-file-6.png
touch created-file-7.txt
touch created-file-8.png
touch created-file-9.txt
touch created-file-10.png
